server:
 port: 8080
 servlet.context-path: /layercache-example

spring:
  profiles:
    active: dev
  application:
    name: layercache-example

layering-cache:
  namespace: layering-cache-web
  stats: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
