server:
 port: 8080
 servlet.context-path: /swagger-example

spring:
  application:
    name: swagger-example
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static/,classpath:/static/html/,classpath:/static/js/
