server:
 port: 8080
 servlet.context-path: /session-example

spring:
  session:
    redis:
      flush-mode: on_save
      namespace: session.example
      cleanup-cron: 0 * * * * *
    store-type: redis
    timeout: PT10M
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: PT10M
        max-idle: 10
        min-idle: 10
    database: 0
  profiles:
    active: dev
  application:
    name: session-example